/* Team: 2014NissanPathFinder
Veer Bhagia (vbhagia@calpoly.edu)
Brooke Saaty (bsaaty@calpoly.edu)
Davis Morales (dmoral45@calpoly.edu)
Jonathan Martin (jmart663@calpoly.edu)*/

DROP TABLE EQUIPtoROOM;

DROP TABLE DEPTOCCUPANT;

DROP TABLE ROOMOCCUPANTS;

DROP TABLE LOGRECORDS;

DROP TABLE EQUIPMENTACTIONS;

DROP TABLE ACTIONS;

DROP TABLE USERS;

DROP TABLE ROOMIMAGES;

DROP TABLE STAFFandFACULTY;

DROP TABLE DEPARTMENTS;

DROP TABLE COLLEGES;

DROP TABLE EQUIPMENT;

DROP TABLE ROOMS;

DROP TABLE FLOORPLANS;

DROP TABLE ROOMTYPE;

DROP TABLE FLOORS;

DROP TABLE BUILDINGS;

