/* Team: 2014NissanPathFinder
Veer Bhagia (vbhagia@calpoly.edu)
Brooke Saaty (bsaaty@calpoly.edu)
Davis Morales (dmoral45@calpoly.edu)
Jonathan Martin (jmart663@calpoly.edu)*/

CREATE TABLE BUILDINGS(
BNumber VARCHAR(100) PRIMARY KEY,
BName VARCHAR(100) UNIQUE NOT NULL,
BFloorCount INT);

CREATE TABLE FLOORS(
BNumber VARCHAR(100),
FNumber INT,
CONSTRAINT FK_BNumberFLoors
    FOREIGN KEY (BNumber)
    REFERENCES BUILDINGS(BNumber),
PRIMARY KEY(BNumber, FNumber));

CREATE TABLE ROOMTYPE(
TypeId INT PRIMARY KEY,
TypeName VARCHAR(100) UNIQUE NOT NULL);

CREATE TABLE ROOMSPACE(
TypeId INT PRIMARY KEY,
TypeName VARCHAR(100) UNIQUE NOT NULL);

CREATE TABLE FLOORPLANS(
FImagePath VARCHAR(400) PRIMARY KEY,
BNumber VARCHAR(100) NOT NULL,
FNumber INT NOT NULL,
CONSTRAINT FK_FLoorsFPlans
    FOREIGN KEY (BNumber, FNumber)
    REFERENCES FLOORS(BNumber, FNumber));

CREATE TABLE ROOMS(
BNumber VARCHAR(100),
RNumber VARCHAR(100),
SqFt FLOAT, 
BoxCoordinates POLYGON,
HasBackup BIT,
FNumber INT,
FBNumber VARCHAR(100),
RoomType INT,
RoomSpace INT
CONSTRAINT FK_BNumberRooms
    FOREIGN KEY (BNumber)
    REFERENCES BUILDINGS(BNumber),
PRIMARY KEY(BNumber, RNumber),
CONSTRAINT FK_FNumberRooms
    FOREIGN KEY (FBNumber, FNumber)
    REFERENCES FLOORS(BNumber, FNumber),
CONSTRAINT FK_RoomRType
    FOREIGN KEY (RoomType)
    REFERENCES ROOMTYPE(TypeId));
CONSTRAINT FK_RoomRSpace
    FOREIGN KEY (RoomSpace)
    REFERENCES ROOMSPACE(TypeId));

CREATE TABLE EQUIPMENT(
TypeId INT PRIMARY KEY,
EquipName VARCHAR(100) UNIQUE NOT NULL,
isSensitive BIT);

CREATE TABLE COLLEGES(
Abbreviation VARCHAR(100) PRIMARY KEY,
CName VARCHAR(100) UNIQUE NOT NULL);

CREATE TABLE DEPARTMENTS(
DId VARCHAR(100) PRIMARY KEY,
DName VARCHAR(100) UNIQUE,
College VARCHAR(100),
CONSTRAINT FK_DeptCollege
    FOREIGN KEY (College)
    REFERENCES COLLEGES(Abbreviation));

CREATE TABLE STAFFandFACULTY(
Email VARCHAR(100) PRIMARY KEY,
FirstName VARCHAR(100),
LastName VARCHAR(100),
Title VARCHAR(100),
DeptID INT,
CONSTRAINT FK_StaffDept
    FOREIGN KEY (DeptID)
    REFERENCES DEPARTMENTS(DId));

CREATE TABLE ROOMIMAGES(
RImagePath VARCHAR(400) PRIMARY KEY,
RNumber VARCHAR(100),
BNumber VARCHAR(100),
CONSTRAINT FK_RImagesRooms
    FOREIGN KEY (BNumber, RNumber)
    REFERENCES ROOMS(BNumber, RNumber));
    
CREATE TABLE USERS(
Email VARCHAR(100) PRIMARY KEY,
FirstName VARCHAR(100),
LastName VARCHAR(100),
URole VARCHAR(100),
UPassword VARCHAR(100));

CREATE TABLE ACTIONS(
    AId INT PRIMARY KEY,
    Descript VARCHAR(300)
);

CREATE TABLE EQUIPMENTACTIONS(
    ActionID INT,
    EquipID INT,
    Duration VARCHAR(100),
    CONSTRAINT FK_EquipType
        FOREIGN KEY (EquipID)
        REFERENCES EQUIPMENT(TypeId),
    CONSTRAINT FK_ActionID
        FOREIGN KEY (ActionID)
        REFERENCES ACTIONS(AId),
    PRIMARY KEY(ActionID, EquipID)
);

CREATE TABLE LOGRECORDS(
ActionId INT PRIMARY KEY,
RTime TIMESTAMP UNIQUE NOT NULL,
RType VARCHAR(100),
RUser VARCHAR(100) NOT NULL,
RAction VARCHAR(200),
RNumber VARCHAR(100) NOT NULL,
BNumber VARCHAR(100) NOT NULL,
DeptID INT,
Email VARCHAR(100),
EquipID INT,
CONSTRAINT FK_UserLog
    FOREIGN KEY (RUser)
    REFERENCES USERS(Email),
CONSTRAINT FK_LogsRooms
    FOREIGN KEY (BNumber, RNumber)
    REFERENCES ROOMS(BNumber, RNumber),
CONSTRAINT FK_LogsDept
    FOREIGN KEY (DeptID)
    REFERENCES DEPARTMENTS(DId),
CONSTRAINT FK_LogsEmail
    FOREIGN KEY (Email)
    REFERENCES STAFFandFACULTY(Email),
CONSTRAINT FK_LogsEquipType
    FOREIGN KEY (EquipID)
    REFERENCES EQUIPMENT(TypeId));

CREATE TABLE ROOMOCCUPANTS(
Email VARCHAR(100),
BNumber VARCHAR(100),
RNumber VARCHAR(100),
DateAssigned TIMESTAMP,
CONSTRAINT FK_OccupEmail
    FOREIGN KEY (Email)
    REFERENCES STAFFandFACULTY(Email),
CONSTRAINT FK_OccupRooms
    FOREIGN KEY (BNumber, RNumber)
    REFERENCES ROOMS(BNumber, RNumber),
PRIMARY KEY(Email, BNumber, RNumber));

CREATE TABLE DEPTOCCUPANT(
DeptID INT,
BNumber VARCHAR(100),
RNumber VARCHAR(100),
Quantity INT,
DateAssigned TIMESTAMP,
CONSTRAINT FK_DeptOccup
    FOREIGN KEY (DeptID)
    REFERENCES DEPARTMENTS(DId),
CONSTRAINT FK_DeptOccupRooms
    FOREIGN KEY (BNumber, RNumber)
    REFERENCES ROOMS(BNumber, RNumber),
PRIMARY KEY(DeptID, BNumber, RNumber));

CREATE TABLE EQUIPtoROOM(
EquipType INT,
RNumber VARCHAR(100),
BNumber VARCHAR(100),
DateAssigned TIMESTAMP,
Comments VARCHAR(200),
CONSTRAINT FK_EquipTypeRooms
    FOREIGN KEY (EquipType)
    REFERENCES EQUIPMENT(TypeId),
CONSTRAINT FK_EquipRooms
    FOREIGN KEY (BNumber, RNumber)
    REFERENCES ROOMS(BNumber, RNumber),
PRIMARY KEY(EquipType, BNumber, RNumber));

CREATE TABLE CONTACTPERSONS(
    EquipType INT,
    RNumber VARCHAR(100),
    BNumber VARCHAR(100),
    Email VARCHAR(100),
    Type VARCHAR(7),
    CONSTRAINT FK_EquipContact
        FOREIGN KEY (EquipType)
        REFERENCES EQUIPMENT(TypeId),
    CONSTRAINT FK_RoomContact
        FOREIGN KEY (BNumber, RNumber)
        REFERENCES ROOMS(BNumber, RNumber),
    CONSTRAINT FK_ContactEmail
        FOREIGN KEY (Email)
        REFERENCES STAFFandFACULTY(Email),
    PRIMARY KEY(EquipType, BNumber, RNumber, Email));
)